export const USER_INFO_LOADING = 'USER_INFO_LOADING';
export const USER_INFO_LOADED = 'USER_INFO_LOADED';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';

export const USER_MEDIA_LOADING = 'USER_MEDIA_LOADING';
export const USER_MEDIA_LOADED = 'USER_MEDIA_LOADED';
export const USER_MEDIA_ERROR = 'USER_MEDIA_ERROR';

export const SAVE_TOKEN = 'SAVE_TOKEN';

export const LIKE_MEDIA = 'LIKE_MEDIA';
export const LOAD_LIKES = 'LOAD_LIKES';

export const FILTER_SHOW_ONLY_FAVORITES = 'FILTER_SHOW_ONLY_FAVORITES';
export const FILTER_BY_TAG_AND_DESC = 'FILTER_BY_TAG_AND_DESC';